# Generated by Django 4.2.30 on 2026-09-10 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='allow_download',
            field=models.BooleanField(default=False, verbose_name='是否允许下载'),
        ),
    ]
